from langchain_core.messages import AIMessage


class Description(AIMessage):
    """Description of current screenshot, generated by AI"""

    ...


class Action(AIMessage):
    """Action generated by AI"""

    ...


class ActionFailure(AIMessage):
    """Action failure observed by AI"""

    ...


class Difference(AIMessage):
    """Difference casued by an action, observed by AI"""

    ...


class Summary(AIMessage):
    """The task related to full actions, summarized by AI"""

    ...
